name: Build, Test and Lint

on:
  push:
    branches: [ develop, main ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: install packages
      run: sudo apt-get install libxcb-render0-dev libxcb-shape0-dev libxcb-xfixes0-dev
    - name: Lint
      run: cargo clippy -- -D warnings
    - name: Test
      run: cargo test --verbose 